### PR TITLE
feat: add bilibili dark theme

### PR DESCRIPTION
**Pull request by smileorigin**
# Pull Request Template

## Name of theme

Bilibili Dark

## How Has This Been Tested?

I ran python3 ./scripts/gen_theme_previews.py standard to generate the preview

### CODE REVIEW

**Comment by elviskahoro** [comment]
@smileorigin thanks for opening this! Are you in our discord? if so I can add the contributor role!

**Comment by smileorigin** [comment]
> @smileorigin thanks for opening this! Are you in our discord? if so I can add the contributor role!

Thanks @elviskahoro for merging this 
Yes I'm in discord. Email: smileorigin@foxmail.com

**Comment by smileorigin** [comment]
@elviskahoro My username is smileorigin

**Comment by elviskahoro** [comment]
@smileorigin added the role!

**Pull request merged**
