### PR TITLE
Theme: GitHub Dark Dimmed

### PR DESCRIPTION
**Pull request by heymage**

### CODE REVIEW

**Comment by elviskahoro** [comment]
@heymage thanks for doing this. Are you in our Discord server? If so what's your username so I can add the contributor discord role?

**Comment by heymage** [comment]
Hey @elviskahoro, I just joined the server, my username is `heymage`

**Comment by yamatsum** [comment]
@heymage 
Is this color code accurate?
It looks different from the official thing.
https://github.com/primer/primitives/blob/main/data/colors/themes/dark_dimmed.ts

**Comment by heymage** [comment]
> @heymage Is this color code accurate? It looks different from the official thing. https://github.com/primer/primitives/blob/main/data/colors/themes/dark_dimmed.ts

Which color do you mean exactly? I changed the brightBlack font color a bit to be readable on dark backgrounds. All other colors are taken from the GitHub website with Dimmed Theme.

**Comment by yamatsum** [comment]
@heymage 
Thank you for your reply!
Most of the colors specified here seem to be [Dark](https://github.com/primer/primitives/blob/main/data/colors/themes/dark.ts), not [Dark Dimmed](https://github.com/primer/primitives/blob/main/data/colors/themes/dark_dimmed.ts).
For example, accent colors(#F78166) do not exist in Dark Dimmed. It seems to be #EC775C correctly

**Comment by heymage** [comment]
Interesting. I didn't know that these files exist tbh. I will update the theme as soon as I've got time. Thank you for pointing that out 👍🏻

**Pull request merged**
